import { SourceDoc } from '../types';

/**
 * Liste de sources de départ, amorcée en base par `seedSources`. Miroir de
 * `mobile/lib/config/default_sources.dart` — la collection Firestore
 * `sources` est la source de vérité une fois amorcée ; ces deux fichiers ne
 * sont utilisés qu'à l'initialisation ou comme référence hors-ligne.
 */
export const DEFAULT_SOURCES: Record<string, SourceDoc> = {
  lefaso_net: {
    nom: 'LeFaso.net',
    domaine: 'lefaso.net',
    fluxRss: 'https://lefaso.net/spip.php?page=backend',
    methodeCollecte: 'rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  burkina24: {
    nom: 'Burkina24',
    domaine: 'burkina24.com',
    fluxRss: 'https://burkina24.com/feed/',
    methodeCollecte: 'rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  sidwaya: {
    nom: 'Sidwaya',
    domaine: 'sidwaya.bf',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  lobservateur: {
    nom: "L'Observateur Paalga",
    domaine: 'lobservateur.bf',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  lepays: {
    nom: 'Le Pays',
    domaine: 'lepays.bf',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  aujourd8: {
    nom: "Aujourd'hui au Faso",
    domaine: 'aujourd8.net',
    fluxRss: 'https://aujourd8.net/feed/',
    methodeCollecte: 'rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  wakatsera: {
    nom: 'Wakat Séra',
    domaine: 'wakatsera.com',
    fluxRss: 'https://wakatsera.com/feed/',
    methodeCollecte: 'rss',
    categorie: 'presseBf',
    accesPayant: false,
    actif: true,
  },
  leconomiste_du_faso: {
    nom: "L'Économiste du Faso",
    domaine: 'leconomistedufaso.bf',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseEcoBf',
    accesPayant: false,
    actif: true,
  },
  echos_du_faso: {
    nom: 'Les Échos du Faso',
    domaine: 'echosdufaso.com',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseEcoBf',
    accesPayant: false,
    actif: true,
  },
  investir_au_burkina: {
    nom: 'Investir au Burkina',
    domaine: 'investirauburkina.net',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseEcoBf',
    accesPayant: false,
    actif: true,
  },
  minefid: {
    nom: 'MINEFID',
    domaine: 'finances.gov.bf',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'institution',
    accesPayant: false,
    actif: true,
  },
  bceao: {
    nom: 'BCEAO',
    domaine: 'bceao.int',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'institution',
    accesPayant: false,
    actif: true,
  },
  uemoa: {
    nom: 'Commission UEMOA',
    domaine: 'uemoa.int',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'institution',
    accesPayant: false,
    actif: true,
  },
  boad: {
    nom: 'BOAD',
    domaine: 'boad.org',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'institution',
    accesPayant: false,
    actif: true,
  },
  brvm: {
    nom: 'BRVM',
    domaine: 'brvm.org',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'institution',
    accesPayant: false,
    actif: true,
  },
  agence_ecofin: {
    nom: 'Agence Ecofin',
    domaine: 'agenceecofin.com',
    fluxRss: 'https://www.agenceecofin.com/rss',
    methodeCollecte: 'rss',
    categorie: 'presseRegionale',
    accesPayant: false,
    actif: true,
  },
  financial_afrik: {
    nom: 'Financial Afrik',
    domaine: 'financialafrik.com',
    fluxRss: 'https://www.financialafrik.com/feed/',
    methodeCollecte: 'rss',
    categorie: 'presseRegionale',
    accesPayant: false,
    actif: true,
  },
  sika_finance: {
    nom: 'Sika Finance',
    domaine: 'sikafinance.com',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseRegionale',
    accesPayant: false,
    actif: true,
  },
  apa_news: {
    nom: 'APA News',
    domaine: 'apanews.net',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseRegionale',
    accesPayant: false,
    actif: true,
  },
  la_tribune_afrique: {
    nom: 'La Tribune Afrique',
    domaine: 'afrique.latribune.fr',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'presseRegionale',
    accesPayant: false,
    actif: true,
  },
  jeune_afrique: {
    nom: 'Jeune Afrique — Économie',
    domaine: 'jeuneafrique.com',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'international',
    accesPayant: true,
    actif: true,
  },
  africa_report: {
    nom: 'The Africa Report',
    domaine: 'theafricareport.com',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'international',
    accesPayant: true,
    actif: true,
  },
  reuters_africa: {
    nom: 'Reuters — Africa',
    domaine: 'reuters.com',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'international',
    accesPayant: false,
    actif: true,
  },
  imf_bfa: {
    nom: 'FMI — Burkina Faso',
    domaine: 'imf.org',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'international',
    accesPayant: false,
    actif: true,
  },
  banque_mondiale_bf: {
    nom: 'Banque mondiale — Burkina Faso',
    domaine: 'banquemondiale.org',
    fluxRss: null,
    methodeCollecte: 'google_news_rss',
    categorie: 'international',
    accesPayant: false,
    actif: true,
  },
};
